# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aulasena

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_6506f6fd571a4dab87c6ca4fe0bd044e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bd87f27757ec4cffbc26c806feb8b5f1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6506f6fd571a4dab87c6ca4fe0bd044e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aulasena'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5eefd2cfd15d424190309e65b7bc2bca }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6506f6fd571a4dab87c6ca4fe0bd044e }}/appsvc/staticsite:${{ github.sha }}'